import { Song } from '@/types/song';

/**
 * Initial sample repertoire songs matching source project default library.
 */
export const INITIAL_SONGS: Song[] = [
  {
    id: '1',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    originalKey: 'Bb Major',
    content: '{title: Bohemian Rhapsody}\n{key: Bb}\n\n[Bb]Is this the [Gm]real life?\n[Bb]Is this just [Gm]fantasy?',
    isFavorite: false,
    tags: ['rock'],
    fontScale: 1,
  },
  {
    id: '2',
    title: 'Fly Me To The Moon',
    artist: 'Frank Sinatra',
    originalKey: 'C Minor',
    content: '{title: Fly Me To The Moon}\n{key: Am}\n\n[Am]Fly me to the [Dm7]moon\nLet me [G7]play among the [Cmaj7]stars',
    isFavorite: true,
    tags: ['jazz'],
    fontScale: 1,
  },
  {
    id: '3',
    title: 'Hotel California',
    artist: 'Eagles',
    originalKey: 'B Minor',
    content: '{title: Hotel California}\n{key: Bm}\n\n[Bm]On a dark desert [F#7]highway\n[A]Cool wind in my [E]hair',
    isFavorite: false,
    tags: ['rock'],
    fontScale: 1,
  },
  {
    id: '4',
    title: 'Autumn Leaves',
    artist: 'Joseph Kosma',
    originalKey: 'G Minor',
    content: '{title: Autumn Leaves}\n{key: Gm}\n\n[Cm7]The falling [F7]leaves\n[Bbmaj7]Drift by my [Ebmaj7]window',
    isFavorite: true,
    tags: ['jazz'],
    fontScale: 1,
  },
  {
    id: '5',
    title: 'Wonderwall',
    artist: 'Oasis',
    originalKey: 'F# Minor',
    content: "{title: Wonderwall}\n{key: F#m}\n\n[F#m]Today is gonna be the day\nThat they're gonna [A]throw it back to [E]you",
    isFavorite: false,
    tags: ['rock'],
    fontScale: 1,
  },
  {
    id: '6',
    title: 'All The Things You Are',
    artist: 'Jerome Kern',
    originalKey: 'Ab Major',
    content: '{title: All The Things You Are}\n{key: Ab}\n\n[Fm7]You [Bbm7]are the\n[Eb7]promised [Abmaj7]kiss of springtime',
    isFavorite: false,
    tags: ['jazz'],
    fontScale: 1,
  },
  {
    id: '7',
    title: 'Blue Bossa',
    artist: 'Kenny Dorham',
    originalKey: 'C Minor',
    content: '{title: Blue Bossa}\n{key: Cm}\n\n[Cm]Blue [Fm7]bossa\n[Dm7b5]So [G7]fine',
    isFavorite: true,
    tags: ['jazz'],
    fontScale: 1,
  },
  {
    id: '8',
    title: 'Take Five',
    artist: 'Paul Desmond',
    originalKey: 'Eb Minor',
    content: '{title: Take Five}\n{key: Ebm}\n\n[Ebm]Take [Bbm7]five\n[Ebm]Take [Bbm7]five',
    isFavorite: false,
    tags: ['jazz'],
    fontScale: 1,
  },
];
